export const GET_VIDEOS_REQUEST = "GET_VIDEOS_REQUEST";
export const GET_VIDEOS_SUCCESS = "GET_VIDEOS_SUCCESS";
export const GET_VIDEOS_FAILURE = "GET_VIDEOS_FAILURE";
export const GET_CURRVIDEO_SUCCESS = "GET_CURRVIDEO_SUCCESS";
export const GET_CURRVIDEO_REQUEST = "GET_CURRVIDEO_REQUEST";
export const GET_CURRVIDEO_FAILURE = "GET_CURRVIDEO_FAILURE";